server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yoga1?characterEncoding=UTF8
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .jsp
